# Custom SwiftLint configuration

disabled_rules:
  - line_length

statement_position:
  statement_mode: uncuddled_else

force_cast:
  severity: warning

file_length:
  warning: 700
  ignore_comment_only_lines: true

for_where:
  allow_for_as_filter: true
